#!/usr/bin/env bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$DIR/.."
GOOS=linux GOARCH=amd64 make
cp powerdns-consul "$DIR/"
cd "$DIR"
./build

for backend in consul etcd; do
  echo "Testing with backend $backend"
  docker run -it --rm -e DEBUG=1 sh4rk/powerdns-consul-end2end "$backend"
done
